---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: my-atomic-os
# description will be included in the image's metadata
description: ThinkPad T480 config 

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files:
        - vscode.repo
      copr:
        - sneexy/python-validity
      keys:
        - https://packages.microsoft.com/keys/microsoft.asc
      nonfree: rpmfusion

    install:
      packages:
        - mozilla-openh264
        - python3-validity
        - code
        - rust
        - cargo
        - clippy
        - rustfmt
        - rust-src
        - lm_sensors
        - stress-ng
        - intel-media-driver
        - python3-pip
        - rclone
        - chromium
        - distrobox
        - gh
        - cmake
        - glibc-devel
        - fastfetch
        - tlp
        - tlp-rdw
        - gnome-backgrounds-extras

    remove:
      packages:
        - tuned 
        - tuned-ppd
        - fedora-workstation-backgrounds
        - desktop-backgrounds-gnome
        - f42-backgrounds-gnome
        - gnome-classic-session
        - gnome-shell-extension-apps-menu
        - gnome-shell-extension-launch-new-instance
        - gnome-shell-extension-places-menu
        - gnome-shell-extension-window-list

    group-install:
      with-optional: true # install optional packages from group
      packages:
        - virtualization

  - type: script
    scripts:
      - codecs.sh

  - type: systemd
    system:
      enabled:
        - podman.socket 
        - open-fprintd.service 
        - python3-validity.service 
        - open-fprintd-restart-after-resume.service 
        - python3-validity-restart-after-resume.service 
        - libvirtd.service
        - tlp.service

      disabled:
        - open-fprintd-resume.service
        - open-fprintd-suspend.service

  
  - from-file: add-mod.yml
  - from-file: chezmoi.yml
  - from-file: gnome-extensions.yml
  - from-file: flatpak.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

